pub const SaverType = enum {
    None,
    Caller,
    Callee,
};

pub const Abbr = enum(u5) {
    zero = 0,
    gp = 1,
    sp = 2,
    fp = 3,
    lr = 4,
    t0 = 5,
    t1 = 6,
    t2 = 7,
    t3 = 8,
    t4 = 9,
    t5 = 10,
    rv = 11,
    f0 = 12,
    f1 = 13,
    f2 = 14,
    f3 = 15,
    f4 = 16,
    f5 = 17,
    f6 = 18,
    f7 = 19,
    s0 = 20,
    s1 = 21,
    s2 = 22,
    s3 = 23,
    s4 = 24,
    s5 = 25,
    s6 = 26,
    s7 = 27,
    s8 = 28,
    s9 = 29,
    s10 = 30,
    s11 = 31,
};

pub const RegInfo = struct {
    abbr: Abbr,
    saver: SaverType,
};

pub const Registers: [32]RegInfo = .{
    .{ .abbr = .zero, .saver = .None },
    .{ .abbr = .gp, .saver = .None },
    .{ .abbr = .sp, .saver = .Callee },
    .{ .abbr = .fp, .saver = .Callee },
    .{ .abbr = .lr, .saver = .Callee },
    .{ .abbr = .t0, .saver = .Caller },
    .{ .abbr = .t1, .saver = .Caller },
    .{ .abbr = .t2, .saver = .Caller },
    .{ .abbr = .t3, .saver = .Caller },
    .{ .abbr = .t4, .saver = .Caller },
    .{ .abbr = .t5, .saver = .Caller },
    .{ .abbr = .rv, .saver = .Caller },
    .{ .abbr = .f0, .saver = .Caller },
    .{ .abbr = .f1, .saver = .Caller },
    .{ .abbr = .f2, .saver = .Caller },
    .{ .abbr = .f3, .saver = .Caller },
    .{ .abbr = .f4, .saver = .Caller },
    .{ .abbr = .f5, .saver = .Caller },
    .{ .abbr = .f6, .saver = .Caller },
    .{ .abbr = .f7, .saver = .Caller },
    .{ .abbr = .s0, .saver = .Callee },
    .{ .abbr = .s1, .saver = .Callee },
    .{ .abbr = .s2, .saver = .Callee },
    .{ .abbr = .s3, .saver = .Callee },
    .{ .abbr = .s4, .saver = .Callee },
    .{ .abbr = .s5, .saver = .Callee },
    .{ .abbr = .s6, .saver = .Callee },
    .{ .abbr = .s7, .saver = .Callee },
    .{ .abbr = .s8, .saver = .Callee },
    .{ .abbr = .s9, .saver = .Callee },
    .{ .abbr = .s10, .saver = .Callee },
    .{ .abbr = .s11, .saver = .Callee },
};
