pub const SaverType = enum {
    None,
    Caller,
    Callee,
};

pub const Abbr = enum(u5) {
    zero = 0,
    gp = 1,
    sp = 2,
    fp = 3,
    lr = 4,
    t0 = 5,
    t1,
    t2,
    t3,
    t4,
    t5,
    rv = 11,
    f0 = 12,
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    s0 = 24,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
};

pub const RegInfo = struct {
    abbr: Abbr,
    saver: SaverType,
};

pub const Registers: [32]RegInfo = .{
    .{ .abbr = .zero, .saver = .None },
    .{ .abbr = .gp, .saver = .None },
    .{ .abbr = .sp, .saver = .Callee },
    .{ .abbr = .fp, .saver = .Callee },
    .{ .abbr = .lr, .saver = .Callee },
    .{ .abbr = .t0, .saver = .Caller },
    .{ .abbr = .t1, .saver = .Caller },
    .{ .abbr = .t2, .saver = .Caller },
    .{ .abbr = .t3, .saver = .Caller },
    .{ .abbr = .t4, .saver = .Caller },
    .{ .abbr = .t5, .saver = .Caller },
    .{ .abbr = .rv, .saver = .Caller },
    .{ .abbr = .f0, .saver = .Caller },
    .{ .abbr = .f1, .saver = .Caller },
    .{ .abbr = .f2, .saver = .Caller },
    .{ .abbr = .f3, .saver = .Caller },
    .{ .abbr = .f4, .saver = .Caller },
    .{ .abbr = .f5, .saver = .Caller },
    .{ .abbr = .f6, .saver = .Caller },
    .{ .abbr = .f7, .saver = .Caller },
    .{ .abbr = .s0, .saver = .Callee },
    .{ .abbr = .s1, .saver = .Callee },
    .{ .abbr = .s2, .saver = .Callee },
    .{ .abbr = .s3, .saver = .Callee },
    .{ .abbr = .s4, .saver = .Callee },
    .{ .abbr = .s5, .saver = .Callee },
    .{ .abbr = .s6, .saver = .Callee },
    .{ .abbr = .s7, .saver = .Callee },
    .{ .abbr = .s8, .saver = .Callee },
    .{ .abbr = .s9, .saver = .Callee },
    .{ .abbr = .s10, .saver = .Callee },
    .{ .abbr = .s11, .saver = .Callee },
};
